# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ara}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gregoire Lejeune"]
  s.date = %q{2011-07-15}
  s.description = %q{Ara is a tiny class that’s allow you to use actors in Ruby}
  s.email = %q{gregoire.lejeune@free.fr}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ara.gemspec",
    "examples/actor.erl",
    "examples/actor.rb",
    "examples/actor.scala",
    "examples/async_actor.rb",
    "examples/async_block.rb",
    "examples/async_meth.rb",
    "examples/logger_actor.rb",
    "examples/simple_actor.rb",
    "examples/simple_scheduler.rb",
    "examples/sync_actor.rb",
    "examples/test_actor.rb",
    "examples/ws-client.rb",
    "examples/ws.rb",
    "lib/ara.rb",
    "lib/ara/actor.rb",
    "lib/ara/actors.rb",
    "lib/ara/exception.rb",
    "lib/ara/logger.rb",
    "lib/ara/remote.rb",
    "lib/ara/remote_actor.rb",
    "lib/ara/scheduler.rb",
    "lib/ara/simple_actor.rb",
    "lib/ext/binding_of_caller.rb",
    "test/helper.rb",
    "test/test_ara.rb"
  ]
  s.homepage = %q{http://algorithmique.net}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9.2")
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A tiny Actor class}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

